import type {
  ConversationListItem,
  ConversationDetail,
  MessageItem,
} from "./types";

// ─── Sample Messages ─────────────────────────────────────────────

export const SAMPLE_MESSAGES: MessageItem[] = [
  {
    id: "msg-001",
    conversationId: "conv-001",
    senderType: "app_user",
    senderName: "李娜",
    content: "您好，我想咨询家族滞在签证的更新手续。",
    kind: "text",
    visibleScope: "client_visible",
    translationStatus: "completed",
    translatedContent:
      "こんにちは、家族滞在ビザの更新手続きについて相談したいです。",
    createdAt: "2026-04-27T09:00:00Z",
    createdAtLabel: "09:00",
  },
  {
    id: "msg-002",
    conversationId: "conv-001",
    senderType: "staff",
    senderName: "铃木",
    content:
      "李娜さん、お問い合わせありがとうございます。家族滞在ビザの更新に必要な書類をご案内します。",
    kind: "text",
    visibleScope: "client_visible",
    translationStatus: "completed",
    translatedContent:
      "李娜女士，感谢您的咨询。我来为您介绍家族滞在签证更新所需的材料。",
    createdAt: "2026-04-27T09:05:00Z",
    createdAtLabel: "09:05",
  },
  {
    id: "msg-003",
    conversationId: "conv-001",
    senderType: "staff",
    senderName: "铃木",
    content: "",
    kind: "intake_link",
    visibleScope: "client_visible",
    translationStatus: "none",
    translatedContent: null,
    createdAt: "2026-04-27T09:06:00Z",
    createdAtLabel: "09:06",
  },
  {
    id: "msg-004",
    conversationId: "conv-001",
    senderType: "app_user",
    senderName: "李娜",
    content: "好的，我已经收到了问卷链接，稍后填写。",
    kind: "text",
    visibleScope: "client_visible",
    translationStatus: "failed",
    translatedContent: null,
    createdAt: "2026-04-27T09:10:00Z",
    createdAtLabel: "09:10",
  },
  {
    id: "msg-005",
    conversationId: "conv-001",
    senderType: "staff",
    senderName: "System",
    content: "会话已分配给铃木。",
    kind: "system_event",
    visibleScope: "client_visible",
    translationStatus: "none",
    translatedContent: null,
    createdAt: "2026-04-27T08:55:00Z",
    createdAtLabel: "08:55",
  },
];

// ─── Sample Conversations ────────────────────────────────────────

export const SAMPLE_CONVERSATION_LIST: ConversationListItem[] = [
  {
    id: "conv-001",
    channel: "web",
    preferredLanguage: "zh",
    status: "open",
    ownerUserId: "suzuki",
    ownerLabel: "铃木",
    lastMessagePreview: "好的，我已经收到了问卷链接，稍后填写。",
    lastMessageAt: "2026-04-27T09:10:00Z",
    lastMessageAtLabel: "今天 09:10",
    unreadCountUser: 0,
    unreadCountStaffTenant: 1,
    unreadCountStaffOwner: 1,
    linkedEntity: {
      id: "LEAD-2026-0045",
      label: "李娜 — 家族滞在",
      type: "lead",
    },
    appUserName: "李娜",
  },
  {
    id: "conv-002",
    channel: "line",
    preferredLanguage: "ja",
    status: "open",
    ownerUserId: "tanaka",
    ownerLabel: "田中",
    lastMessagePreview:
      "見積書を確認しました。サインの手続きを教えてください。",
    lastMessageAt: "2026-04-27T08:30:00Z",
    lastMessageAtLabel: "今天 08:30",
    unreadCountUser: 0,
    unreadCountStaffTenant: 0,
    unreadCountStaffOwner: 0,
    linkedEntity: {
      id: "cust-003",
      label: "山田太郎 — 经营管理签",
      type: "customer",
    },
    appUserName: "山田太郎",
  },
  {
    id: "conv-003",
    channel: "web",
    preferredLanguage: "en",
    status: "open",
    ownerUserId: null,
    ownerLabel: "",
    lastMessagePreview: "Hello, I need help with my work visa application.",
    lastMessageAt: "2026-04-27T07:45:00Z",
    lastMessageAtLabel: "今天 07:45",
    unreadCountUser: 0,
    unreadCountStaffTenant: 2,
    unreadCountStaffOwner: 0,
    linkedEntity: null,
    appUserName: "John Smith",
  },
  {
    id: "conv-004",
    channel: "wechat",
    preferredLanguage: "zh",
    status: "closed",
    ownerUserId: "suzuki",
    ownerLabel: "铃木",
    lastMessagePreview: "感谢您的帮助，签证已经顺利更新。",
    lastMessageAt: "2026-04-25T16:00:00Z",
    lastMessageAtLabel: "04-25 16:00",
    unreadCountUser: 0,
    unreadCountStaffTenant: 0,
    unreadCountStaffOwner: 0,
    linkedEntity: {
      id: "CAS-2026-0181",
      label: "李娜 家族滞在更新",
      type: "case",
    },
    appUserName: "李娜（旧）",
  },
];

// ─── Sample Detail ───────────────────────────────────────────────

export const SAMPLE_CONVERSATION_DETAIL: ConversationDetail = {
  id: "conv-001",
  channel: "web",
  preferredLanguage: "zh",
  status: "open",
  ownerUserId: "suzuki",
  ownerLabel: "铃木",
  leadId: "LEAD-2026-0045",
  customerId: null,
  caseId: null,
  appUserName: "李娜",
  linkedLead: {
    id: "LEAD-2026-0045",
    label: "李娜 — 家族滞在",
    type: "lead",
  },
  linkedCustomer: null,
  linkedCase: null,
  messages: SAMPLE_MESSAGES,
  unreadCountUser: 0,
  unreadCountStaffTenant: 1,
  unreadCountStaffOwner: 1,
  createdAt: "2026-04-27T08:50:00Z",
};

export const SAMPLE_CONVERSATION_DETAIL_CLOSED: ConversationDetail = {
  ...SAMPLE_CONVERSATION_DETAIL,
  id: "conv-004",
  status: "closed",
  ownerLabel: "铃木",
  leadId: null,
  customerId: "cust-001",
  caseId: "CAS-2026-0181",
  appUserName: "李娜（旧）",
  linkedLead: null,
  linkedCustomer: {
    id: "cust-001",
    label: "李娜",
    type: "customer",
  },
  linkedCase: {
    id: "CAS-2026-0181",
    label: "李娜 家族滞在更新",
    type: "case",
  },
  messages: SAMPLE_MESSAGES.slice(0, 2),
  unreadCountUser: 0,
  unreadCountStaffTenant: 0,
  unreadCountStaffOwner: 0,
  createdAt: "2026-04-20T10:00:00Z",
};
