import type { RequirementBlueprintItem } from "../../../modules/core/cases/cases.types-template-blueprints";

export const BUSINESS_MANAGER_VISA_REQUIREMENT_BLUEPRINT: RequirementBlueprintItem[] =
  [
    {
      checklistItemCode: "bmv-passport-copy",
      name: "パスポートコピー",
      category: "personal",
      requiredFlag: true,
      ownerSide: "applicant",
      providedByRole: "applicant",
      sortOrder: 1,
    },
    {
      checklistItemCode: "bmv-photo",
      name: "証明写真（4cm×3cm）",
      category: "personal",
      requiredFlag: true,
      ownerSide: "applicant",
      providedByRole: "applicant",
      sortOrder: 2,
    },
    {
      checklistItemCode: "bmv-resume",
      name: "履歴書",
      category: "personal",
      requiredFlag: true,
      ownerSide: "applicant",
      providedByRole: "applicant",
      sortOrder: 3,
    },
    {
      checklistItemCode: "bmv-business-plan",
      name: "事業計画書",
      category: "company",
      requiredFlag: true,
      ownerSide: "office",
      providedByRole: "office",
      sortOrder: 4,
      description: "行政書士事務所が作成",
    },
    {
      checklistItemCode: "bmv-company-registry",
      name: "法人登記簿謄本",
      category: "company",
      requiredFlag: true,
      ownerSide: "customer",
      providedByRole: "employer",
      sortOrder: 5,
    },
    {
      checklistItemCode: "bmv-office-lease",
      name: "事務所賃貸契約書",
      category: "company",
      requiredFlag: true,
      ownerSide: "customer",
      providedByRole: "employer",
      sortOrder: 6,
    },
    {
      checklistItemCode: "bmv-capital-proof",
      name: "資本金振込証明",
      category: "company",
      requiredFlag: true,
      ownerSide: "customer",
      providedByRole: "employer",
      sortOrder: 7,
    },
    {
      checklistItemCode: "bmv-office-photos",
      name: "事務所写真",
      category: "company",
      requiredFlag: false,
      ownerSide: "customer",
      providedByRole: "employer",
      sortOrder: 8,
      description: "事務所の内部・外観写真",
    },
    {
      checklistItemCode: "bmv-financial-statement",
      name: "決算報告書",
      category: "company",
      requiredFlag: false,
      ownerSide: "customer",
      providedByRole: "employer",
      sortOrder: 9,
      description: "更新・既存法人の場合に必要",
    },
    {
      checklistItemCode: "bmv-business-overview",
      name: "事業概要説明書",
      category: "company",
      requiredFlag: false,
      ownerSide: "office",
      providedByRole: "office",
      sortOrder: 10,
    },
  ];
