import type { RequirementBlueprintItem } from "../../../modules/core/cases/cases.types-template-blueprints";

export const FAMILY_STAY_REQUIREMENT_BLUEPRINT: RequirementBlueprintItem[] = [
  {
    checklistItemCode: "fs-passport-copy",
    name: "パスポートコピー",
    category: "personal",
    requiredFlag: true,
    ownerSide: "applicant",
    sortOrder: 1,
  },
  {
    checklistItemCode: "fs-photo",
    name: "証明写真（4cm×3cm）",
    category: "personal",
    requiredFlag: true,
    ownerSide: "applicant",
    sortOrder: 2,
  },
  {
    checklistItemCode: "fs-residence-card",
    name: "在留カードコピー",
    category: "personal",
    requiredFlag: true,
    ownerSide: "applicant",
    sortOrder: 3,
  },
  {
    checklistItemCode: "fs-marriage-cert",
    name: "婚姻証明書（戸籍謄本）",
    category: "personal",
    requiredFlag: true,
    ownerSide: "applicant",
    sortOrder: 4,
    description:
      "配偶者が日本人の場合は戸籍謄本、外国人同士の場合は本国の婚姻証明書",
  },
  {
    checklistItemCode: "fs-supporter-tax-cert",
    name: "扶養者の納税証明書",
    category: "standard",
    requiredFlag: true,
    ownerSide: "customer",
    sortOrder: 5,
  },
  {
    checklistItemCode: "fs-supporter-employment",
    name: "扶養者の在職証明書",
    category: "standard",
    requiredFlag: true,
    ownerSide: "customer",
    sortOrder: 6,
  },
  {
    checklistItemCode: "fs-supporter-residence-card",
    name: "扶養者の在留カードコピー",
    category: "standard",
    requiredFlag: true,
    ownerSide: "customer",
    sortOrder: 7,
  },
  {
    checklistItemCode: "fs-reason-statement",
    name: "申請理由書",
    category: "standard",
    requiredFlag: true,
    ownerSide: "office",
    sortOrder: 8,
    description: "行政書士事務所が作成",
  },
  {
    checklistItemCode: "fs-application-form",
    name: "在留資格認定/変更許可申請書",
    category: "standard",
    requiredFlag: true,
    ownerSide: "office",
    sortOrder: 9,
    description: "行政書士事務所が作成・提出",
  },
  {
    checklistItemCode: "fs-guarantee-letter",
    name: "身元保証書",
    category: "standard",
    requiredFlag: true,
    ownerSide: "customer",
    sortOrder: 10,
  },
];
