import type { RequirementBlueprintItem } from "../../../modules/core/cases/cases.types-template-blueprints";

export const WORK_VISA_REQUIREMENT_BLUEPRINT: RequirementBlueprintItem[] = [
  {
    checklistItemCode: "work-passport-copy",
    name: "パスポートコピー",
    category: "personal",
    requiredFlag: true,
    ownerSide: "applicant",
    providedByRole: "applicant",
    sortOrder: 1,
  },
  {
    checklistItemCode: "work-photo",
    name: "証明写真（4cm×3cm）",
    category: "personal",
    requiredFlag: true,
    ownerSide: "applicant",
    providedByRole: "applicant",
    sortOrder: 2,
  },
  {
    checklistItemCode: "work-resume",
    name: "履歴書",
    category: "personal",
    requiredFlag: true,
    ownerSide: "applicant",
    providedByRole: "applicant",
    sortOrder: 3,
  },
  {
    checklistItemCode: "work-diploma",
    name: "卒業証明書（学位証明書）",
    category: "personal",
    requiredFlag: true,
    ownerSide: "applicant",
    providedByRole: "applicant",
    sortOrder: 4,
    description:
      "学歴を証明する書類。学歴要件を満たさない場合は実務経験証明書で代替",
  },
  {
    checklistItemCode: "work-employment-contract",
    name: "雇用契約書",
    category: "company",
    requiredFlag: true,
    ownerSide: "customer",
    providedByRole: "supporter",
    sortOrder: 5,
  },
  {
    checklistItemCode: "work-company-registry",
    name: "会社の登記事項証明書",
    category: "company",
    requiredFlag: true,
    ownerSide: "customer",
    providedByRole: "supporter",
    sortOrder: 6,
  },
  {
    checklistItemCode: "work-company-profile",
    name: "会社案内（パンフレット等）",
    category: "company",
    requiredFlag: true,
    ownerSide: "customer",
    providedByRole: "supporter",
    sortOrder: 7,
  },
  {
    checklistItemCode: "work-financial-statement",
    name: "直近の決算報告書",
    category: "company",
    requiredFlag: true,
    ownerSide: "customer",
    providedByRole: "supporter",
    sortOrder: 8,
  },
  {
    checklistItemCode: "work-reason-statement",
    name: "申請理由書",
    category: "standard",
    requiredFlag: true,
    ownerSide: "office",
    providedByRole: "office",
    sortOrder: 9,
    description: "行政書士事務所が作成",
  },
  {
    checklistItemCode: "work-application-form",
    name: "在留資格認定/変更許可申請書",
    category: "standard",
    requiredFlag: true,
    ownerSide: "office",
    providedByRole: "office",
    sortOrder: 10,
    description: "行政書士事務所が作成・提出",
  },
  {
    checklistItemCode: "work-category-proof",
    name: "カテゴリー証明書類",
    category: "company",
    requiredFlag: false,
    ownerSide: "customer",
    providedByRole: "supporter",
    sortOrder: 11,
    description: "カテゴリー1〜3に該当する場合の証明書（法定調書合計表等）",
  },
];
