import type {
  CustomerCase,
  CustomerComm,
  CustomerDetail,
  CustomerLog,
  CustomerRelation,
  CustomerSummary,
  CustomerViewerContext,
  SelectOption,
  SummaryCardData,
} from "./types";

export const SAMPLE_CUSTOMERS: CustomerSummary[] = [
  {
    id: "cust-001",
    displayName: "田中太郎",
    legalName: "田中太郎",
    furigana: "タナカタロウ",
    customerNumber: "C-20240001",
    phone: "090-1234-5678",
    email: "tanaka@example.com",
    totalCases: 3,
    activeCases: 1,
    lastContactDate: "2025-04-10",
    lastContactChannel: "電話",
    owner: { initials: "YS", name: "山田翔太" },
    referralSource: "紹介（佐藤様）",
    group: "東京一組",
  },
  {
    id: "cust-002",
    displayName: "陈明",
    legalName: "陈明",
    furigana: "チンメイ",
    customerNumber: "C-20240002",
    phone: "080-9876-5432",
    email: "chen@example.com",
    totalCases: 2,
    activeCases: 2,
    lastContactDate: "2025-04-12",
    lastContactChannel: "メール",
    owner: { initials: "YS", name: "山田翔太" },
    referralSource: "Web 問い合わせ",
    group: "東京一組",
  },
  {
    id: "cust-003",
    displayName: "Li Wei",
    legalName: "Li Wei",
    furigana: "リウェイ",
    customerNumber: "C-20240003",
    phone: "",
    email: "liwei@example.com",
    totalCases: 1,
    activeCases: 0,
    lastContactDate: null,
    lastContactChannel: null,
    owner: { initials: "TK", name: "高橋健太" },
    referralSource: "",
    group: "大阪組",
  },
  {
    id: "cust-004",
    displayName: "佐藤美咲",
    legalName: "佐藤美咲",
    furigana: "サトウミサキ",
    customerNumber: "C-20240004",
    phone: "070-8888-1208",
    email: "misaki.sato@example.jp",
    totalCases: 0,
    activeCases: 0,
    lastContactDate: "2026-04-09",
    lastContactChannel: "メール",
    owner: { initials: "TK", name: "高橋健太" },
    referralSource: "広告（経営管理）",
    group: "東京一組",
  },
];

export const SAMPLE_SUMMARY: SummaryCardData[] = [
  { key: "mine", variant: "primary", value: 12 },
  { key: "group", variant: "info", value: 38 },
  { key: "active", variant: "warning", value: 22 },
  { key: "noActive", variant: "neutral", value: 16 },
];

export const CURRENT_VIEWER: CustomerViewerContext = {
  ownerName: "山田翔太",
  group: "東京一組",
};

export const GROUP_OPTIONS: SelectOption[] = [
  { value: "tokyo-1", label: "東京一組" },
  { value: "tokyo-2", label: "東京二組" },
  { value: "osaka", label: "大阪組" },
];

export const OWNER_OPTIONS: SelectOption[] = [
  { value: "yamada-s", label: "山田翔太" },
  { value: "takahashi-k", label: "高橋健太" },
  { value: "suzuki-a", label: "鈴木あかり" },
];

export const SAMPLE_CASES_BY_CUSTOMER: Record<string, CustomerCase[]> = {
  "cust-001": [
    {
      id: "CASE-2026-0412",
      name: "田中太郎｜経営管理1年更新",
      type: "経営管理更新",
      stage: "資料収集中",
      status: "active",
      owner: "山田翔太",
      createdAt: "2025-03-20",
      updatedAt: "2025-04-08",
    },
    {
      id: "CASE-2025-1100",
      name: "田中太郎｜会社設立",
      type: "会社設立",
      stage: "完了・アーカイブ",
      status: "archived",
      owner: "山田翔太",
      createdAt: "2024-09-01",
      updatedAt: "2025-01-15",
    },
    {
      id: "CASE-2024-0830",
      name: "田中太郎｜技人国→経営管理変更",
      type: "在留資格変更",
      stage: "完了・アーカイブ",
      status: "archived",
      owner: "山田翔太",
      createdAt: "2024-06-10",
      updatedAt: "2024-11-30",
    },
  ],
  "cust-002": [
    {
      id: "CASE-2026-0503",
      name: "陳明｜経営管理4ヶ月認定",
      type: "経営管理認定",
      stage: "提出前確認",
      status: "active",
      owner: "山田翔太",
      createdAt: "2025-04-01",
      updatedAt: "2025-04-10",
    },
    {
      id: "CASE-2026-0521",
      name: "陳明｜経営管理1年更新",
      type: "経営管理更新",
      stage: "資料収集中",
      status: "active",
      owner: "高橋健太",
      createdAt: "2025-03-15",
      updatedAt: "2025-04-05",
    },
  ],
  "cust-003": [
    {
      id: "CASE-2024-1201",
      name: "Li Wei｜技人国認定（完了）",
      type: "技人国認定",
      stage: "完了・アーカイブ",
      status: "archived",
      owner: "高橋健太",
      createdAt: "2024-12-15",
      updatedAt: "2025-03-01",
    },
  ],
  "cust-004": [],
};

export const SAMPLE_RELATIONS_BY_CUSTOMER: Record<string, CustomerRelation[]> =
  {
    "cust-001": [
      {
        id: "REL-001-1",
        name: "田中花子",
        kana: "タナカハナコ",
        relationType: "spouse",
        phone: "090-8765-4321",
        email: "hanako.t@example.com",
        tags: ["家族", "緊急連絡先"],
        note: "補件の際に連絡可能",
      },
    ],
    "cust-002": [
      {
        id: "REL-002-1",
        name: "陳小明",
        kana: "チンショウメイ",
        relationType: "parent",
        phone: "",
        email: "xiaoming.c@example.com",
        tags: ["家族"],
        note: "中国在住・資金証明関連",
      },
      {
        id: "REL-002-2",
        name: "佐藤行政書士事務所",
        kana: "サトウギョウセイショシジムショ",
        relationType: "agent",
        phone: "03-1234-5678",
        email: "info@sato-office.jp",
        tags: ["紹介元"],
        note: "継続的に案件を紹介",
      },
    ],
    "cust-003": [],
    "cust-004": [],
  };

export const SAMPLE_COMMS_BY_CUSTOMER: Record<string, CustomerComm[]> = {
  "cust-001": [
    {
      id: "COM-001-1",
      type: "phone",
      visibility: "customer",
      occurredAt: "2026-04-10T14:30",
      actor: "山田翔太",
      summary: "确认补件时间表",
      detail: "客户承诺下周前补齐在职证明与住民税课税证明。",
      nextAction: "2026-04-17 跟进资料到齐情况",
    },
    {
      id: "COM-001-2",
      type: "wechat",
      visibility: "internal",
      occurredAt: "2026-04-08T10:00",
      actor: "山田翔太",
      summary: "内部讨论更新方案",
      detail: "与主管确认更新方案可直接走标准路径。",
      nextAction: "",
    },
    {
      id: "COM-001-3",
      type: "email",
      visibility: "customer",
      occurredAt: "2026-03-28T11:30",
      actor: "山田翔太",
      summary: "发送资料清单邮件",
      detail: "将经营管理更新所需资料清单发送给客户。",
      nextAction: "等待客户回复确认",
    },
  ],
  "cust-002": [
    {
      id: "COM-002-1",
      type: "meeting",
      visibility: "customer",
      occurredAt: "2026-04-12T15:00",
      actor: "山田翔太",
      summary: "面谈确认认定申请细节",
      detail: "确认公司设立进度与经营管理签4ヶ月认定的资料完整度。",
      nextAction: "2026-04-15 催收公司注册证明副本",
    },
  ],
  "cust-003": [],
  "cust-004": [],
};

export const SAMPLE_LOGS_BY_CUSTOMER: Record<string, CustomerLog[]> = {
  "cust-001": [
    {
      id: "LOG-001-1",
      type: "info",
      actor: "山田翔太",
      at: "2026-04-10T14:35",
      message: "更新基础信息：电话、邮箱",
    },
    {
      id: "LOG-001-2",
      type: "comm",
      actor: "山田翔太",
      at: "2026-04-10T14:30",
      message: "新增沟通记录：电话 · 确认补件时间表（客户可见）",
    },
    {
      id: "LOG-001-3",
      type: "case",
      actor: "山田翔太",
      at: "2026-03-20T09:00",
      message: "创建案件：经営管理1年更新",
    },
    {
      id: "LOG-001-4",
      type: "relation",
      actor: "山田翔太",
      at: "2026-03-15T11:00",
      message: "新增关联人：田中花子（配偶）",
    },
  ],
  "cust-002": [
    {
      id: "LOG-002-1",
      type: "comm",
      actor: "山田翔太",
      at: "2026-04-12T15:05",
      message: "新增沟通记录：面谈 · 确认认定申请细节（客户可见）",
    },
    {
      id: "LOG-002-2",
      type: "case",
      actor: "山田翔太",
      at: "2026-04-01T10:00",
      message: "创建案件：経営管理4ヶ月認定",
    },
    {
      id: "LOG-002-3",
      type: "relation",
      actor: "高橋健太",
      at: "2026-03-20T14:00",
      message: "新增关联人：陳小明（父母）",
    },
  ],
  "cust-003": [
    {
      id: "LOG-003-1",
      type: "case",
      actor: "高橋健太",
      at: "2024-12-15T09:30",
      message: "创建案件：技人国認定",
    },
  ],
  "cust-004": [],
};

export const SAMPLE_CUSTOMER_DETAILS: Record<string, CustomerDetail> = {
  "cust-001": {
    id: "cust-001",
    displayName: "田中太郎",
    legalName: "田中太郎",
    furigana: "タナカタロウ",
    customerNumber: "C-20240001",
    phone: "090-1234-5678",
    email: "tanaka@example.com",
    totalCases: 3,
    activeCases: 1,
    archivedCases: 2,
    lastContactDate: "2025-04-10",
    lastContactChannel: "電話",
    owner: { initials: "YS", name: "山田翔太" },
    referralSource: "紹介（佐藤様）",
    group: "東京一組",
    nationality: "日本",
    gender: "男",
    birthDate: "1985-06-15",
    avatar: "",
    note: "ビジネス拡大に伴う在留資格変更を検討中",
    caseNames: ["経営管理1年更新", "会社設立", "技人国 → 経営管理 変更"],
    lastCaseCreatedDate: "2025-03-20",
  },
  "cust-002": {
    id: "cust-002",
    displayName: "陈明",
    legalName: "陈明",
    furigana: "チンメイ",
    customerNumber: "C-20240002",
    phone: "080-9876-5432",
    email: "chen@example.com",
    totalCases: 2,
    activeCases: 2,
    archivedCases: 0,
    lastContactDate: "2025-04-12",
    lastContactChannel: "メール",
    owner: { initials: "YS", name: "山田翔太" },
    referralSource: "Web 問い合わせ",
    group: "東京一組",
    nationality: "中国",
    gender: "男",
    birthDate: "1990-11-03",
    avatar: "",
    note: "",
    caseNames: ["経営管理4ヶ月認定", "経営管理1年更新"],
    lastCaseCreatedDate: "2025-04-01",
  },
  "cust-003": {
    id: "cust-003",
    displayName: "Li Wei",
    legalName: "Li Wei",
    furigana: "リウェイ",
    customerNumber: "C-20240003",
    phone: "",
    email: "liwei@example.com",
    totalCases: 1,
    activeCases: 0,
    archivedCases: 1,
    lastContactDate: null,
    lastContactChannel: null,
    owner: { initials: "TK", name: "高橋健太" },
    referralSource: "",
    group: "大阪組",
    nationality: "中国",
    gender: "男",
    birthDate: "1988-02-28",
    avatar: "",
    note: "",
    caseNames: ["技人国 認定（完了）"],
    lastCaseCreatedDate: "2024-12-15",
  },
  "cust-004": {
    id: "cust-004",
    displayName: "佐藤美咲",
    legalName: "佐藤美咲",
    furigana: "サトウミサキ",
    customerNumber: "C-20240004",
    phone: "070-8888-1208",
    email: "misaki.sato@example.jp",
    totalCases: 0,
    activeCases: 0,
    archivedCases: 0,
    lastContactDate: "2026-04-09",
    lastContactChannel: "メール",
    owner: { initials: "TK", name: "高橋健太" },
    referralSource: "広告（経営管理）",
    group: "東京一組",
    nationality: "日本",
    gender: "女",
    birthDate: "1995-07-22",
    avatar: "",
    note: "経営管理ビザの新規取得を検討中",
    caseNames: [],
    lastCaseCreatedDate: null,
  },
};
