/** validation-runs / review-records / submission-packages 写接口错误码（admin i18n 映射）。 */
export const VALIDATION_SUBMISSION_ERROR_CODES = {
  VR_CASE_NOT_FOUND: "VR_CASE_NOT_FOUND",
  VR_CASE_S9_READONLY: "VR_CASE_S9_READONLY",
  VR_NOT_FOUND: "VR_NOT_FOUND",
  RR_CASE_NOT_FOUND: "RR_CASE_NOT_FOUND",
  RR_CASE_S9_READONLY: "RR_CASE_S9_READONLY",
  RR_NOT_FOUND: "RR_NOT_FOUND",
  RR_INVALID_DECISION: "RR_INVALID_DECISION",
  RR_VALIDATION_RUN_NOT_LATEST: "RR_VALIDATION_RUN_NOT_LATEST",
  SP_CASE_NOT_FOUND: "SP_CASE_NOT_FOUND",
  SP_NOT_FOUND: "SP_NOT_FOUND",
  SP_CASE_STAGE_INVALID: "SP_CASE_STAGE_INVALID",
  SP_SUPPLEMENT_REQUIRES_RELATED: "SP_SUPPLEMENT_REQUIRES_RELATED",
  SP_INITIAL_NO_RELATED: "SP_INITIAL_NO_RELATED",
  SP_RELATED_NOT_FOUND: "SP_RELATED_NOT_FOUND",
  SP_RELATED_NOT_LATEST: "SP_RELATED_NOT_LATEST",
  SP_RELATED_ALREADY_BRANCHED: "SP_RELATED_ALREADY_BRANCHED",
  SP_CHAIN_DEPTH_EXCEEDED: "SP_CHAIN_DEPTH_EXCEEDED",
  SP_INVALID_SUBMISSION_KIND: "SP_INVALID_SUBMISSION_KIND",
  SP_INVALID_ITEM_TYPE: "SP_INVALID_ITEM_TYPE",
  SP_DUPLICATE_ITEM: "SP_DUPLICATE_ITEM",
  SP_MISSING_MINIMUM_FIELDS: "SP_MISSING_MINIMUM_FIELDS",
} as const;

/** Validation/submission 错误码联合类型。 */
export type ValidationSubmissionErrorCode =
  (typeof VALIDATION_SUBMISSION_ERROR_CODES)[keyof typeof VALIDATION_SUBMISSION_ERROR_CODES];
