import type { LeadDetail } from "./types";
import { LEAD_DETAIL_SAMPLES_EXTRA } from "./fixtures-detail-extra";

/**
 * 详情页示例数据：核心场景（S.1–S.4）。
 */
const CORE_SAMPLES: Record<string, LeadDetail> = {
  /* ====== S.1  正常跟进态 ====== */
  following: {
    id: "LEAD-2026-0035",
    name: "李华",
    status: "following",
    ownerId: "tanaka",
    ownerLabel: "田中",
    ownerInitials: "田",
    ownerAvatarClass: "bg-emerald-100 text-emerald-700",
    groupId: "tokyo-1",
    groupLabel: "东京一组",
    banner: null,
    buttons: "normal",
    readonly: false,
    info: {
      id: "LEAD-2026-0035",
      name: "李华",
      phone: "080-2222-3333",
      email: "li.hua@email.com",
      source: "介绍",
      referrer: "佐藤弁護士",
      businessType: "家族滞在",
      group: "东京一组",
      owner: "田中",
      language: "中文",
      note: "配偶在日永住者，希望尽快提交认定申请。首选语言中文。",
    },
    followups: [
      {
        channel: "email",
        channelLabel: "邮件",
        summary:
          "发送家族滞在认定材料清单（主申请人 + 扶养者），附件含示例模板。",
        conclusion: "客户确认收到，预计本周内开始准备",
        nextAction: "跟进材料上传情况",
        nextFollowUp: "2026-04-15",
        time: "2026/04/09 10:00",
        operator: "田中",
      },
      {
        channel: "phone",
        channelLabel: "电话",
        summary: "致电确认意向与基本资料情况，客户表示配偶在日居住 5 年以上。",
        conclusion: "意向明确，进入资料准备阶段",
        nextAction: "邮件发送材料清单",
        nextFollowUp: "2026-04-12",
        time: "2026/04/08 14:30",
        operator: "田中",
      },
      {
        channel: "meeting",
        channelLabel: "面谈",
        summary: "初次面谈，了解家庭构成、扶养者在日状况、签约意向。",
        conclusion: "基本信息确认，建议配偶准备纳税/课税证明",
        nextAction: "电话确认意向",
        nextFollowUp: "2026-04-08",
        time: "2026/04/05 15:00",
        operator: "田中",
      },
    ],
    conversion: {
      dedupResult: null,
      convertedCustomer: null,
      convertedCase: null,
      conversions: [],
    },
    log: [
      {
        type: "status",
        operator: "田中",
        time: "2026/04/08 14:30",
        fromValue: "新咨询",
        toValue: "跟进中",
        chipClass: "bg-sky-100 text-sky-700",
      },
      {
        type: "owner",
        operator: "管理员",
        time: "2026/04/07 09:00",
        fromValue: "田中",
        toValue: "铃木",
        chipClass: "bg-emerald-100 text-emerald-700",
      },
      {
        type: "group",
        operator: "管理员",
        time: "2026/04/06 10:00",
        fromValue: "东京一组",
        toValue: "东京二组",
        chipClass: "bg-violet-100 text-violet-700",
      },
      {
        type: "status",
        operator: "田中",
        time: "2026/04/05 16:00",
        fromValue: "—",
        toValue: "新咨询",
        chipClass: "bg-amber-100 text-amber-700",
      },
    ],
  },

  /* ====== S.2  已流失态 ====== */
  lost: {
    id: "LEAD-2026-0019",
    name: "佐藤 美咲",
    status: "lost",
    ownerId: "tanaka",
    ownerLabel: "田中",
    ownerInitials: "田",
    ownerAvatarClass: "bg-emerald-100 text-emerald-700",
    groupId: "tokyo-1",
    groupLabel: "东京一组",
    banner: "lost",
    buttons: "lost",
    readonly: true,
    info: {
      id: "LEAD-2026-0019",
      name: "佐藤 美咲",
      phone: "090-4444-1111",
      email: "sato.misaki@email.com",
      source: "电话",
      referrer: "",
      businessType: "永住",
      group: "东京一组",
      owner: "田中",
      language: "日语",
      note: "曾咨询永住申请。三次跟进未回复后标记为流失。",
    },
    followups: [
      {
        channel: "phone",
        channelLabel: "电话",
        summary: "第三次致电仍无人接听，留言后标记为流失。",
        conclusion: "连续三次无回应，标记流失",
        nextAction: "",
        nextFollowUp: "",
        time: "2026/03/28 15:00",
        operator: "田中",
      },
      {
        channel: "phone",
        channelLabel: "电话",
        summary: "第二次致电未接听，留语音留言。",
        conclusion: "未联系上",
        nextAction: "一周后再次致电",
        nextFollowUp: "2026-03-28",
        time: "2026/03/21 10:30",
        operator: "田中",
      },
    ],
    conversion: {
      dedupResult: null,
      convertedCustomer: null,
      convertedCase: null,
      conversions: [],
    },
    log: [
      {
        type: "status",
        operator: "田中",
        time: "2026/03/28 15:30",
        fromValue: "跟进中",
        toValue: "已流失",
        chipClass: "bg-gray-200 text-gray-600",
      },
      {
        type: "status",
        operator: "铃木",
        time: "2026/03/14 14:30",
        fromValue: "新咨询",
        toValue: "跟进中",
        chipClass: "bg-sky-100 text-sky-700",
      },
      {
        type: "status",
        operator: "系统",
        time: "2026/03/14 09:00",
        fromValue: "—",
        toValue: "新咨询",
        chipClass: "bg-amber-100 text-amber-700",
      },
    ],
  },

  /* ====== S.3  已签约未转化态 ====== */
  signed: {
    id: "LEAD-2026-0022",
    name: "陈 大伟",
    status: "signed",
    ownerId: "suzuki",
    ownerLabel: "铃木",
    ownerInitials: "铃",
    ownerAvatarClass: "bg-sky-100 text-sky-700",
    groupId: "tokyo-1",
    groupLabel: "东京一组",
    banner: "signedNotConverted",
    buttons: "signedNotConverted",
    readonly: false,
    info: {
      id: "LEAD-2026-0022",
      name: "陈 大伟",
      phone: "080-9999-0000",
      email: "chen.dw@email.com",
      source: "网站表单",
      referrer: "",
      businessType: "家族滞在",
      group: "东京一组",
      owner: "铃木",
      language: "中文",
      note: "已确认签约意向，合同已签。待创建客户档案与案件。",
    },
    followups: [
      {
        channel: "meeting",
        channelLabel: "面谈",
        summary: "签约面谈，确认费用与服务范围，签署委任合同。",
        conclusion: "合同已签，转入客户建档",
        nextAction: "创建客户档案并建案",
        nextFollowUp: "2026-04-09",
        time: "2026/04/05 14:00",
        operator: "铃木",
      },
      {
        channel: "phone",
        channelLabel: "电话",
        summary: "致电确认签约意向，客户同意下周面谈。",
        conclusion: "确认下周三面谈",
        nextAction: "安排面谈",
        nextFollowUp: "2026-04-05",
        time: "2026/04/02 11:00",
        operator: "铃木",
      },
    ],
    conversion: {
      dedupResult: null,
      convertedCustomer: null,
      convertedCase: null,
      conversions: [],
    },
    log: [
      {
        type: "status",
        operator: "铃木",
        time: "2026/04/05 15:00",
        fromValue: "待签约",
        toValue: "已签约",
        chipClass: "bg-emerald-100 text-emerald-700",
      },
      {
        type: "status",
        operator: "铃木",
        time: "2026/04/02 11:30",
        fromValue: "跟进中",
        toValue: "待签约",
        chipClass: "bg-violet-100 text-violet-700",
      },
      {
        type: "status",
        operator: "田中",
        time: "2026/03/29 10:00",
        fromValue: "新咨询",
        toValue: "跟进中",
        chipClass: "bg-sky-100 text-sky-700",
      },
      {
        type: "status",
        operator: "系统",
        time: "2026/03/28 09:00",
        fromValue: "—",
        toValue: "新咨询",
        chipClass: "bg-amber-100 text-amber-700",
      },
    ],
  },

  /* ====== S.4  已转客户态 ====== */
  "converted-customer": {
    id: "LEAD-2026-0015",
    name: "王 明",
    status: "signed",
    ownerId: "suzuki",
    ownerLabel: "铃木",
    ownerInitials: "铃",
    ownerAvatarClass: "bg-sky-100 text-sky-700",
    groupId: "tokyo-2",
    groupLabel: "东京二组",
    banner: null,
    buttons: "convertedCustomer",
    readonly: false,
    info: {
      id: "LEAD-2026-0015",
      name: "王 明",
      phone: "080-7777-8888",
      email: "wang.ming@email.com",
      source: "介绍",
      referrer: "山田商事",
      businessType: "技人国",
      group: "东京二组",
      owner: "铃木",
      language: "中文",
      note: "已建立客户档案。技人国更新申请，公司 BlueWave。",
    },
    followups: [
      {
        channel: "meeting",
        channelLabel: "面谈",
        summary: "签约面谈完成，合同签署并创建客户档案。",
        conclusion: "已建档，进入案件创建",
        nextAction: "创建技人国更新案件",
        nextFollowUp: "2026-04-03",
        time: "2026/04/01 14:00",
        operator: "铃木",
      },
      {
        channel: "phone",
        channelLabel: "电话",
        summary: "确认签约意向与所需材料范围。",
        conclusion: "同意签约",
        nextAction: "安排面谈签约",
        nextFollowUp: "2026-04-01",
        time: "2026/03/28 11:00",
        operator: "铃木",
      },
    ],
    conversion: {
      dedupResult: null,
      convertedCustomer: {
        id: "CUS-2026-0195",
        name: "王 明",
        group: "东京二组",
        convertedAt: "2026/04/02",
        convertedBy: "铃木",
      },
      convertedCase: null,
      conversions: [
        {
          type: "customer",
          id: "CUS-2026-0195",
          label: "王 明 → 建立客户档案",
          time: "2026/04/02",
          operator: "铃木",
        },
      ],
    },
    log: [
      {
        type: "status",
        operator: "系统",
        time: "2026/04/02 10:00",
        fromValue: "已签约",
        toValue: "已建客户档案（CUS-2026-0195）",
        chipClass: "bg-emerald-100 text-emerald-700",
      },
      {
        type: "status",
        operator: "铃木",
        time: "2026/04/01 15:00",
        fromValue: "待签约",
        toValue: "已签约",
        chipClass: "bg-emerald-100 text-emerald-700",
      },
      {
        type: "status",
        operator: "系统",
        time: "2026/03/25 09:00",
        fromValue: "—",
        toValue: "新咨询",
        chipClass: "bg-amber-100 text-amber-700",
      },
    ],
  },
};

/**
 * 详情页全部示例数据（8 个场景，覆盖 P0-CONTRACT-DETAIL §9）。
 */
export const LEAD_DETAIL_SAMPLES: Record<string, LeadDetail> = {
  ...CORE_SAMPLES,
  ...LEAD_DETAIL_SAMPLES_EXTRA,
};
