import type { LeadDetail } from "./types";

/**
 * 详情页示例数据：转化态与边缘场景（S.5–S.8）。
 */
export const LEAD_DETAIL_SAMPLES_EXTRA: Record<string, LeadDetail> = {
  /* ====== S.5  已转案件态 ====== */
  "converted-case": {
    id: "LEAD-2026-0015",
    name: "王 明",
    status: "converted_case",
    ownerId: "suzuki",
    ownerLabel: "铃木",
    ownerInitials: "铃",
    ownerAvatarClass: "bg-sky-100 text-sky-700",
    groupId: "tokyo-2",
    groupLabel: "东京二组",
    banner: null,
    buttons: "convertedCase",
    readonly: false,
    info: {
      id: "LEAD-2026-0015",
      name: "王 明",
      phone: "080-7777-8888",
      email: "wang.ming@email.com",
      source: "介绍",
      referrer: "山田商事",
      businessType: "技人国",
      group: "东京二组",
      owner: "铃木",
      language: "中文",
      note: "已建立客户档案并创建案件。技人国更新，CAS-2026-0210 办理中。",
    },
    followups: [
      {
        channel: "meeting",
        channelLabel: "面谈",
        summary: "签约面谈完成，合同签署并创建客户档案。",
        conclusion: "已建档，进入案件创建",
        nextAction: "创建技人国更新案件",
        nextFollowUp: "2026-04-03",
        time: "2026/04/01 14:00",
        operator: "铃木",
      },
    ],
    conversion: {
      dedupResult: null,
      convertedCustomer: {
        id: "CUS-2026-0195",
        name: "王 明",
        group: "东京二组",
        convertedAt: "2026/04/02",
        convertedBy: "铃木",
      },
      convertedCase: {
        id: "CAS-2026-0210",
        title: "王 明 技人国更新",
        type: "技人国 / 更新",
        group: "东京二组",
        convertedAt: "2026/04/03",
        convertedBy: "铃木",
      },
      conversions: [
        {
          type: "customer",
          id: "CUS-2026-0195",
          label: "王 明 → 建立客户档案",
          time: "2026/04/02",
          operator: "铃木",
        },
        {
          type: "case",
          id: "CAS-2026-0210",
          label: "王 明 技人国更新 → 创建案件",
          time: "2026/04/03",
          operator: "铃木",
        },
      ],
    },
    log: [
      {
        type: "status",
        operator: "系统",
        time: "2026/04/03 10:00",
        fromValue: "已建客户档案",
        toValue: "已创建案件（CAS-2026-0210）",
        chipClass: "bg-emerald-100 text-emerald-700",
      },
      {
        type: "status",
        operator: "系统",
        time: "2026/04/02 10:00",
        fromValue: "已签约",
        toValue: "已建客户档案（CUS-2026-0195）",
        chipClass: "bg-emerald-100 text-emerald-700",
      },
      {
        type: "status",
        operator: "铃木",
        time: "2026/04/01 15:00",
        fromValue: "待签约",
        toValue: "已签约",
        chipClass: "bg-emerald-100 text-emerald-700",
      },
    ],
  },

  /* ====== S.6  去重命中 Lead（电话匹配） ====== */
  "dedup-lead": {
    id: "LEAD-2026-0046",
    name: "田中 花子",
    status: "new",
    ownerId: "sato",
    ownerLabel: "佐藤",
    ownerInitials: "佐",
    ownerAvatarClass: "bg-amber-100 text-amber-700",
    groupId: "osaka",
    groupLabel: "大阪组",
    banner: null,
    buttons: "normal",
    readonly: false,
    info: {
      id: "LEAD-2026-0046",
      name: "田中 花子",
      phone: "080-1234-5678",
      email: "",
      source: "电话",
      referrer: "",
      businessType: "高度人才",
      group: "大阪组",
      owner: "佐藤",
      language: "日语",
      note: "电话号码与已有线索 LEAD-2026-0023 重复，经人工确认后继续创建。",
    },
    followups: [
      {
        channel: "phone",
        channelLabel: "电话",
        summary: "来电咨询高度人才签证申请条件与所需材料。",
        conclusion: "初步意向确认，需进一步了解学历和年收入",
        nextAction: "邮件发送高度人才评分表",
        nextFollowUp: "2026-04-14",
        time: "2026/04/09 09:15",
        operator: "佐藤",
      },
    ],
    conversion: {
      dedupResult: {
        type: "lead",
        matchField: "phone",
        matchValue: "080-1234-5678",
        matchedRecord: {
          id: "LEAD-2026-0023",
          name: "田中 花子（既有线索）",
          phone: "080-1234-5678",
          group: "大阪组",
          status: "following",
          statusLabel: "跟进中",
        },
        message:
          '电话号码 080-1234-5678 匹配到已有线索 LEAD-2026-0023（田中 花子），该线索当前为"跟进中"状态。',
        userAction: "confirmed_create",
      },
      convertedCustomer: null,
      convertedCase: null,
      conversions: [],
    },
    log: [
      {
        type: "status",
        operator: "系统",
        time: "2026/04/09 09:15",
        fromValue: "—",
        toValue: "新咨询（确认非重复后创建）",
        chipClass: "bg-amber-100 text-amber-700",
      },
      {
        type: "owner",
        operator: "管理员",
        time: "2026/04/09 09:15",
        fromValue: "—",
        toValue: "佐藤",
        chipClass: "bg-amber-100 text-amber-700",
      },
      {
        type: "group",
        operator: "管理员",
        time: "2026/04/09 09:15",
        fromValue: "—",
        toValue: "大阪组",
        chipClass: "bg-violet-100 text-violet-700",
      },
    ],
  },

  /* ====== S.7  去重命中 Customer（邮箱匹配） ====== */
  "dedup-customer": {
    id: "LEAD-2026-0047",
    name: "李娜（重复确认）",
    status: "new",
    ownerId: "tanaka",
    ownerLabel: "田中",
    ownerInitials: "田",
    ownerAvatarClass: "bg-emerald-100 text-emerald-700",
    groupId: "tokyo-1",
    groupLabel: "东京一组",
    banner: null,
    buttons: "normal",
    readonly: false,
    info: {
      id: "LEAD-2026-0047",
      name: "李娜（重复确认）",
      phone: "",
      email: "li.na@email.com",
      source: "网站表单",
      referrer: "",
      businessType: "家族滞在",
      group: "东京一组",
      owner: "田中",
      language: "中文",
      note: "邮箱与已有客户 CUS-2026-0181（李娜）重复，经人工确认后继续创建新线索。",
    },
    followups: [
      {
        channel: "email",
        channelLabel: "邮件",
        summary:
          "收到网站表单咨询：家族滞在更新相关问题。邮箱匹配到已有客户档案。",
        conclusion: "确认为已有客户的新业务咨询",
        nextAction: "致电确认是否为同一人",
        nextFollowUp: "2026-04-13",
        time: "2026/04/09 10:00",
        operator: "田中",
      },
    ],
    conversion: {
      dedupResult: {
        type: "customer",
        matchField: "email",
        matchValue: "li.na@email.com",
        matchedRecord: {
          id: "CUS-2026-0181",
          name: "李娜",
          email: "li.na@email.com",
          group: "东京一组",
          summary: "已有客户档案，家族滞在更新",
        },
        message:
          "邮箱 li.na@email.com 匹配到已有客户 CUS-2026-0181（李娜），该客户已有档案。",
        userAction: "confirmed_create",
      },
      convertedCustomer: null,
      convertedCase: null,
      conversions: [],
    },
    log: [
      {
        type: "status",
        operator: "系统",
        time: "2026/04/09 10:00",
        fromValue: "—",
        toValue: "新咨询（确认非重复后创建）",
        chipClass: "bg-amber-100 text-amber-700",
      },
      {
        type: "owner",
        operator: "管理员",
        time: "2026/04/09 10:00",
        fromValue: "—",
        toValue: "田中",
        chipClass: "bg-emerald-100 text-emerald-700",
      },
      {
        type: "group",
        operator: "管理员",
        time: "2026/04/09 10:00",
        fromValue: "—",
        toValue: "东京一组",
        chipClass: "bg-violet-100 text-violet-700",
      },
    ],
  },

  /* ====== S.8  空跟进记录态 ====== */
  "empty-followups": {
    id: "LEAD-2026-0042",
    name: "Michael Thompson",
    status: "new",
    ownerId: "suzuki",
    ownerLabel: "铃木",
    ownerInitials: "铃",
    ownerAvatarClass: "bg-sky-100 text-sky-700",
    groupId: "tokyo-1",
    groupLabel: "东京一组",
    banner: null,
    buttons: "normal",
    readonly: false,
    info: {
      id: "LEAD-2026-0042",
      name: "Michael Thompson",
      phone: "090-8765-4321",
      email: "michael.t@email.com",
      source: "网站表单",
      referrer: "",
      businessType: "技人国",
      group: "东京一组",
      owner: "铃木",
      language: "英语",
      note: "刚录入的新线索，尚未开始跟进。",
    },
    followups: [],
    conversion: {
      dedupResult: null,
      convertedCustomer: null,
      convertedCase: null,
      conversions: [],
    },
    log: [
      {
        type: "status",
        operator: "系统",
        time: "2026/04/08 15:30",
        fromValue: "—",
        toValue: "新咨询",
        chipClass: "bg-amber-100 text-amber-700",
      },
      {
        type: "owner",
        operator: "管理员",
        time: "2026/04/08 15:30",
        fromValue: "—",
        toValue: "铃木",
        chipClass: "bg-sky-100 text-sky-700",
      },
      {
        type: "group",
        operator: "管理员",
        time: "2026/04/08 15:30",
        fromValue: "—",
        toValue: "东京一组",
        chipClass: "bg-violet-100 text-violet-700",
      },
    ],
  },
};
